"""Add employer accounts and payment tracking

Revision ID: 049cab5f98fc
Revises: 
Create Date: 2025-07-29 17:55:59.211849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049cab5f98fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'employers', 'employer_accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'employer_accounts', ['employer_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'employers', type_='foreignkey')
    # ### end Alembic commands ###
